name: GitHub-Profile-Blog-Contents

on:
  schedule:
    - cron: '* */24 * * *'
  workflow_dispatch:

jobs:
  profile-updater:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: kumackey/profile-updater@v1
        with:
          zenn_user_id: taka_shino
      - name: Commit and push
        run: |
          git config --local user.name "Takahiro"
          git config --local user.email "tkhr_621@docomo.ne.jp"
          git add .
          git commit -m "profile updated" || true
          git push origin master